### ISSUE TITLE
Aspen chokes on non-ascii filenames on Linux

### ISSUE THREAD

**Issue by techtonik** [gratipay/aspen.py#503]
Tried to follow http://aspen.io/quick-start/ and it fails.

```
$ virtualenv delme
New python executable in delme/bin/python
Installing setuptools, pip...done.
$ cd delme/
$ . bin/activate
delme$ pip install aspen
Downloading/unpacking aspen
  Downloading aspen-0.41-py2-none-any.whl (71kB): 71kB downloaded
...
Successfully installed aspen mimeparse algorithm filesystem-tree first dependency-injection
Cleaning up...
$ echo "XXX!" > index.html.spt
$ python -m aspen
...
pid-22833 thread--1220000000 (MainThread) Greetings, program! Now serving on http://0.0.0.0:8080/.
pid-22833 thread--1220000000 (MainThread) Traceback (most recent call last):
pid-22833 thread--1220000000 (MainThread)   File "/home/techtonik/delme/local/lib/python2.7/site-packages/algorithm.py", line 288, in run
pid-22833 thread--1220000000 (MainThread)     new_state = function(**deps.as_kwargs)
pid-22833 thread--1220000000 (MainThread)   File "/home/techtonik/delme/local/lib/python2.7/site-packages/aspen/algorithms/website.py", line 88, in dispatch_request_to_filesystem
pid-22833 thread--1220000000 (MainThread)     , redirect              = website.redirect
pid-22833 thread--1220000000 (MainThread)   File "/home/techtonik/delme/local/lib/python2.7/site-packages/aspen/dispatcher.py", line 301, in dispatch
pid-22833 thread--1220000000 (MainThread)     , redirect
pid-22833 thread--1220000000 (MainThread)   File "/home/techtonik/delme/local/lib/python2.7/site-packages/aspen/dispatcher.py", line 112, in dispatch_abstract
pid-22833 thread--1220000000 (MainThread)     subnodes = set([ n for n in listnodes(curnode) if not n.startswith('.') ])
pid-22833 thread--1220000000 (MainThread) UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 18: ordinal not in range(128)
pid-22833 thread--1220000000 (MainThread) Failed to import pygments. Tracebacks won't be highlighted.
pid-22833 thread--1220000000 (MainThread) 500 Internal Server Error            /                        ./local/lib/python2.7/site-packages/aspen/www/error.spt
127.0.0.1 - - [14/Aug/2015 19:55:20] "GET / HTTP/1.1" 500 557
```

Okay. It appears that `delme/` directory already existed and there are some unusual filenames there, like "русский". Which is probably why it fails.

**Comment by techtonik** [comment]
Okay. It appears that directory already existed and there is file named "русский" in it. Which is probably why it fails.

**Comment by pjz** [comment]
So the real failure is dealing with unicode filenames?

**Comment by techtonik** [comment]
Most likely.. Let me check..

**Comment by techtonik** [comment]
If I create new directory with just a single `index.html.spt`, it works ok.

**Comment by techtonik** [comment]
Creating file named "русский" (which means Russian) in that empty dir makes it 100% repeatable.

**Comment by pjz** [comment]
good find!

**Comment by techtonik** [comment]
Something tells me that we need an additional layer to access filesystem that will be aware of mounts and encodings. This problem was tried more than one time,

**Comment by pjz** [comment]
soo... I can't repro this.  To do so, I tried:

```
cd /tmp
virtualenv try503
./try503/bin/pip install aspen
mkdir try503/www
echo "Greetings Russian program" >>try503/www/русский.html
ASPEN_WWW_ROOT=/tmp/try503/www ./try503/bin/python -m aspen
```
...and it starts up just fine.  Does that work for you @techtonik ? or does it fail in the way you posted above?

**Comment by techtonik** [comment]
I need to get back to it. I used Ubuntu, but reinstalled it since then.

**Comment by whit537** [comment]
@techtonik Ping?

**Comment by pjz** [comment]
Closing due to needs more info for a very long time.  Reopen iff there's more info.
