### ISSUE TITLE
make docserve fails with OSError

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen.py#511]
Can't find `pip`? I traced into fabricate, and the call arg is `env/bin/pip` and `os.path.isfile` is `True`. Not sure what's going on here ...

```
[aspen]$ make docserve
Passing through to 'python build.py docserve'...
env/bin/pip install -r requirements.txt
Traceback (most recent call last):
  File "build.py", line 300, in <module>
    , ignoreprefix="python"  # workaround for gh190
  File "/Users/whit537/personal/gratipay/aspen.py/fabricate.py", line 1578, in main
    this_status = eval(action, globals_dict)
  File "<string>", line 1, in <module>
  File "build.py", line 132, in docserve
    run(_virt('pip', envdir), 'install', '-r', 'requirements.txt')
  File "/Users/whit537/personal/gratipay/aspen.py/fabricate.py", line 1400, in run
    return default_builder.run(*args, **kwargs)
  File "/Users/whit537/personal/gratipay/aspen.py/fabricate.py", line 1142, in run
    return self._run(*args, **kwargs)
  File "/Users/whit537/personal/gratipay/aspen.py/fabricate.py", line 1125, in _run
    deps, outputs = self.runner(*arglist, **kwargs)
  File "/Users/whit537/personal/gratipay/aspen.py/fabricate.py", line 769, in __call__
    return self._runner(*args, **kwargs)
  File "/Users/whit537/personal/gratipay/aspen.py/fabricate.py", line 432, in __call__
    shell(*args, **shell_keywords)
  File "/Users/whit537/personal/gratipay/aspen.py/fabricate.py", line 163, in shell
    return _shell(args, **kwargs)
  File "/Users/whit537/personal/gratipay/aspen.py/fabricate.py", line 193, in _shell
    raise e
OSError: [Errno 2] No such file or directory
```

**Comment by pjz** [comment]
Cannot repro here.  Try 'make clean docserve' to make sure you've got a clean virtualenv

**Comment by whit537** [comment]
That did it.

!m @pjz
